### ISSUE TITLE
Some syntax error in __init__.py

### ISSUE THREAD

**Issue by Casper133** [painca/pyTemplePriestAPI#3]
<pre>Traceback (most recent call last):
  File &quot;yog_bot.py&quot;, line 10, in &lt;module&gt;
    import templepriest
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 2237, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 2222, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 2164, in _find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1940, in find_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1916, in _get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1897, in _legacy_get_spec
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 863, in spec_from_loader
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 904, in spec_from_file_location
  File &quot;/usr/local/lib/python3.4/dist-packages/pyTemplePriestAPI-0.1-py3.4.egg/templepriest/__init__.py&quot;, line 52
    response = requests.get(req).json()
           ^
SyntaxError: invalid syntax
</pre>

**Comment by painca** [comment]
Починил ошибку, ошибка в забытой скобке выше в _format_
